Correct path to script to test in test-mtbls-dwnld.

diff --git a/test/test-mtbls-dwnld b/test/test-mtbls-dwnld
--- a/test/test-mtbls-dwnld
+++ b/test/test-mtbls-dwnld
@@ -1,6 +1,12 @@
 #!/bin/bash
 # vi: fdm=marker
 
+# Constants {{{1
+################################################################
+
+PROG_NAME=$(basename $0)
+PROG_PATH=$(dirname $0)
+
 # Error {{{1
 ################################################################
 
@@ -38,7 +44,7 @@ for method in $methods ; do
 		if [ $method = ascp ] ; then
 			options+=" -a -t Xz68YfDe"
 		fi
-		../mtbls-dwnld $options /studies/public/$study || error "Download failed !"
+		$PROG_PATH/../mtbls-dwnld $options /studies/public/$study || error "Download failed !"
 
 		# Test downloaded directory
 		[ -d $study ] || error "Download of study $study with $method method failed !"
