Update ASCP connection port. Correct output of unzip function.

diff --git a/mtbls-dwnld b/mtbls-dwnld
--- a/mtbls-dwnld
+++ b/mtbls-dwnld
@@ -199,7 +199,7 @@ function download {
 	# aspera
 	if [ -n "$ASPERA" ] ; then
 
-		dwnld_flags+=" -QT -l 1g"
+		dwnld_flags+=" -QT -l 1g -P33001"
 		[ -n "$(which ascp)" ] || error "ascp command not found. Please install Aspera client."
 
 		export ASPERA_SCP_PASS="$TOKEN"
@@ -276,7 +276,7 @@ function unzip_study {
 	curdir=$(pwd)
 	mkdir $tmp_output
 	cd $tmp_output
-	unzip $unzip_flags "$curdir/$zip" || error "Unable to unzip archive $curdir/$zip."
+	unzip $unzip_flags "$curdir/$zip" >&2 || error "Unable to unzip archive $curdir/$zip."
 	cd $curdir
 
 	echo $tmp_output
