Enable factor slicing in tool XML.

diff --git a/mtbls-dwnld b/mtbls-dwnld
--- a/mtbls-dwnld
+++ b/mtbls-dwnld
@@ -424,13 +424,13 @@ if [[ -n $FACTOR_VALUE ]] ; then
 	[[ -x "$ISASLICER" ]] || error "Cannot find or run isaslicer.py script."
 	print_debug_msg 1 "Run ISA slicer: \"$ISASLICER\" 'isa-tab-get-data-list' \"$dwnld_output\" \"$data_files\" --json-query \"{ \\\"$factor_name\\\": \\\"$factor_value\\\" }\""
 	abs_dwnld_output=$(realpath "$dwnld_output")
-	"$ISASLICER" 'isa-tab-get-data-list' "$abs_dwnld_output" "$data_files" --json-query "{ \"$factor_name\": \"$factor_value\" }"
+	"$ISASLICER" 'isa-tab-get-data-list' "$abs_dwnld_output" "$data_files" --json-query "{ \"$factor_name\": \"$factor_value\" }" 2>&1 || error "Call to isaslicer failed."
 
 	# Download data files
 	get_data_files "$data_files" | sort | uniq | while read file ; do
 		dwnld_flags=
-		[[ $QUIET -eq 0 ]] || dwnld_flags+=" -q"
-		$WGET -O "$dwnld_output/$file" "https://www.ebi.ac.uk/metabolights/$study_name/files/$file"
+		[[ $QUIET -eq 0 ]] || dwnld_flags+="-q"
+		$WGET $dwnld_flags -O "$dwnld_output/$file" "https://www.ebi.ac.uk/metabolights/$study_name/files/$file"
 	done
 
 	# Remove data files list
