List dependencies in README. Redirect stderr of downloader to null.

diff --git a/mtbls-dwnld b/mtbls-dwnld
--- a/mtbls-dwnld
+++ b/mtbls-dwnld
@@ -219,8 +219,9 @@ function download {
 	fi
 
 	# Run download command
+	print_debug_msg 1 "Download command: $(which wget)"
 	print_debug_msg 1 "Download command: $dwnld_cmd"
-	$dwnld_cmd 2>&1
+	$dwnld_cmd 2>/dev/null || error "Downloading of study $STUDY has failed."
 	if [ -f $tmp_output -a ! -s $tmp_output ] ; then
 		echo "Cannot download $tmp_output file. Command \"$dwnld_cmd\" has failed." >&2
 		exit 1
@@ -236,12 +237,14 @@ function unzip_study {
 
 	local tmp_output=$1
 
-	print_debug_msg 1 "Unzipping file $tmp_output."
+	print_debug_msg 1 "Unzipping file \"$tmp_output\"."
 
 	[ -n "$(which unzip)" ] || error "unzip command not found. Please install zip package."
 
 	zip=$tmp_output
+	print_debug_msg 1 "Zipped file is \"$zip\"."
 	tmp_output=${zip%.*}
+	print_debug_msg 1 "Output directory will be \"$tmp_output\"."
 	[[ -d "$tmp_output" ]] && rm -r "$tmp_output"
 	curdir=$(pwd)
 	mkdir $tmp_output
