Quiet output of isatab2w4m. Create Galaxy tests and run them in planemo.

diff --git a/mtbls-dwnld b/mtbls-dwnld
--- a/mtbls-dwnld
+++ b/mtbls-dwnld
@@ -157,7 +157,7 @@ else
 	if [ -n "$METADATA_ONLY" ]; then
 		file=metadata
 	fi
-	dwnld_cmd="wget -O $tmp_output http://www.ebi.ac.uk/metabolights/$(basename $STUDY)/files/$file"
+	dwnld_cmd="wget -q -O $tmp_output http://www.ebi.ac.uk/metabolights/$(basename $STUDY)/files/$file"
 	if [ -n "$TOKEN" ] ; then
 		dwnld_cmd+="?token=$TOKEN"
 	fi
@@ -180,8 +180,8 @@ if [ ${tmp_output##*.} = 'zip' ] ; then
 	curdir=$(pwd)
 	mkdir $tmp_output
 	cd $tmp_output
-	unzip "$curdir/$zip"
-	cd -
+	unzip -qq "$curdir/$zip" || error "Unable to unzip archive $curdir/$zip."
+	cd $curdir
 fi
 
 # Convert to W4M format
@@ -191,7 +191,6 @@ fi
 
 # Write HTML
 if [ -n "$HTML" ] ; then
-	echo "Write HTML output to \"$HTML\"."
 	cat >$HTML <<EOF
 <html>
 	<header>
